name: tf2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - gradio==4.14.0
    - pydantic==2.6.0
    - langchain==0.1.0
    - pypdf==4.0.0
    - python-magic==0.4.27
    - python-magic-bin==0.4.14  # Windows 系统需要
    - sqlalchemy==2.0.25